<h1 align="center"> Logistic Regression</h1>

## Dataset

In [42]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV,train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
from sklearn import metrics
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
import warnings
warnings.filterwarnings("ignore")

In [43]:
#Loading the student dataset for mini-challenges
#Goal is to predict the grade of the student
df = pd.read_csv("../data/student_final.csv")
df.head()

school  sex  age  address  famsize  Pstatus  Medu  Fedu  Mjob  Fjob ...  \
0       0    0    3        1        0        0     4     4     0     4 ...   
1       0    0    2        1        0        1     1     1     0     2 ...   
2       0    0    0        1        1        1     1     1     0     2 ...   
3       0    0    0        1        0        1     4     2     1     3 ...   
4       0    0    1        1        0        1     3     3     2     2 ...   

   internet  romantic  famrel  freetime  goout  Dalc  Walc  health  absences  \
0         0         0       3         2      3     0     0       2         6   
1         1         0       4         2      2     0     0       2         4   
2         1         0       3         2      1     1     2       2        10   
3         1         1       2         1      1     0     0       4         2   
4         0         0       3         2      1     0     1       4         4   

   G1  
0   2  
1   2  
2   4  
3  12  
4   3  

[5 rows x 31 columns]

<img src="../images/icon/ppt-icons.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

##  Mini-Challenge - 1 
***
### Instructions

1. Store the features in the variable `X`.
2. Store the target variable `G1` in the variable `y`.
3. Split the data into `train` and `test`.

In [44]:
#Splitting dataset into features and target variable and splitting them into train and test.
X = df.drop('G1',axis=1)
y = df['G1']
X_train,X_test,y_train,y_test = train_test_split(X,y)

<img src="../images/icon/ppt-icons.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

##  Mini-Challenge - 2
***
### Instructions
1. Fit a logistic regression model on the data and use GridSearchCV to find the optimum number of polynomial features from the list `[2,3,4]` and the best regularization technique from `[l1,l2]`.
2. Then predict on the test dataset and store the result in the variable `y_pred`.

In [45]:
## For a pipeline object
logistic_regressor = LogisticRegression()
pipeline = Pipeline(steps=[('add_poly_features', PolynomialFeatures()),
                           ('logistic_regression', logistic_regressor)])

## Defining the parameters grid
params = {'add_poly_features__degree':[2,3,4],
          'logistic_regression__penalty':['l1','l2']}
grid_search = GridSearchCV(estimator=pipeline, param_grid=params)
grid_search.fit(X_train,y_train)
y_pred = grid_search.predict(X_test)

In [46]:
np.sort(y_test)

array([ 0,  1,  2,  2,  3,  3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 13,
       13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 15, 15, 15])

In [47]:
np.sort(y_pred)

array([ 3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,
        6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 15, 16])

<img src="../images/icon/ppt-icons.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

##  Mini-Challenge - 3
***
### Instructions
* Find the confusion matrix, f1-score of your model.

In [48]:

## code for f-1 score
f1_scor = f1_score(y_test,y_pred,average=None)
print("F1 Score: ",f1_scor)

# Applying confusion matrix on above data
confusion_mat = confusion_matrix(y_test,y_pred)
print("Confusion Matrix: ",confusion_mat)

F1 Score:  [0.         0.         0.         0.         0.         0.125
 0.25       0.07692308 0.16       0.17391304 0.         0.16666667
 0.13333333 0.         0.         0.         0.        ]
Confusion Matrix:  [[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 1 2 0 0 0 0 0]
 [0 0 0 0 5 1 0 0 0 0 0 1 2 0 0 0 0]
 [0 0 0 1 1 0 2 0 3 1 0 0 0 0 0 0 0]
 [0 0 0 1 4 0 3 1 2 4 1 1 0 1 0 0 0]
 [0 0 0 1 1 2 1 0 2 1 1 0 1 1 0 0 1]
 [0 0 0 0 2 0 0 3 1 2 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 2 0 1 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 2 0 1 2 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 0 2 0 1 1 0 1 0 2 0 0 0 0]
 [0 0 0 0 0 1 0 0 1 0 2 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


## Quiz

Q1. True-False: Is Logistic regression a supervised machine learning algorithm?
```python
A) TRUE
B) FALSE
Ans:- A

True, Logistic regression is a supervised learning algorithm because it uses true labels for training. 
Supervised learning algorithm should have input variables (x) and an target variable (Y) when you train the model .
```

Q2. True-False: Is Logistic regression mainly used for Regression?
```python
A) TRUE
B) FALSE

Ans:- B

Logistic regression is a classification algorithm, don’t confuse with the name regression.
```

Q3. True-False: Is it possible to apply a logistic regression algorithm on a 3-class Classification problem?
```python
A) TRUE
B) FALSE

Ans: A

Yes, we can apply logistic regression on 3 classification problem, We can use One Vs all method for 3 class classification in logistic regression.
```

Q4. Which of the following methods do we use to best fit the data in Logistic Regression?
```python
A) Least Square Error
B) Maximum Likelihood
C) Jaccard distance
D) Both A and B

Ans:- B

Logistic regression uses maximum likely hood estimate for training a logistic regression.
```
Q5. Which of the following evaluation metrics can not be applied in case of logistic regression output to compare with target?
```python
A) AUC-ROC
B) Accuracy
C) Logloss
D) Mean-Squared-Error

Ans:- D

Since, Logistic Regression is a classification algorithm so it’s output can not be real time value so mean 
squared error can not use for evaluating it
```
Q6. Which of the following algorithms do we use for Variable Selection?
```python
A) LASSO
B) Ridge
C) Both
D) None of these

Ans:- A

In case of lasso we apply a absolute penality, after increasing the penality in lasso some of the coefficient of variables may become zero.
```


# Thank You
***
### Next Session: Feature Selection
For more queries - Reach out to academics@greyatom.com 